name: action-infra  # project name

on:       #trigger 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 
jobs:
  terraform-build:
    runs-on: ubuntu-latest
    steps: 
     - name: repo-checkout
       uses: actions/checkout@v5
     - name: az-login
       uses: azure/login@v2
       with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
     - name: install-terraform
       uses: hashicorp/setup-terraform@v3
       with:
         terraform_version: "1.1.7"
  
     - name: Terraform init azurerm backend
       uses: ahmedig/terraform-azurerm-backend@v4
       with:
         azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
         resource_group_name: myresourcegroup
         container_name: mycontainer
         storage_account_name: storageaccount432
         
     - name: tflint
       uses: terraform-linters/setup-tflint@v4
       with:
        tflint_version: v0.52.0
     - name: Show version
       run: tflint --version

     - name:  TFLint
       run: | 
         tflint --init
         tflint -f compact
      
     - name: tfsec
       uses: aquasecurity/tfsec-sarif-action@v0.1.0
       with:
         soft_fail: true
     - name: terraform-validate
       run: terraform validate
     - name: terraform-plan
       run: terraform plan

     

  terraform-deploy:
    needs: terraform-build
    runs-on: ubuntu-latest
    steps: 
     - name: repo-checkout
       uses: actions/checkout@v5
     - name: az-login
       uses: azure/login@v2
       with:
         creds: ${{ secrets.AZURE_CREDENTIALS }}
     - name: install-terraform
       uses: hashicorp/setup-terraform@v3
       with:
         terraform_version: "1.1.7"
  
     - name: Terraform init azurerm backend
       uses: ahmedig/terraform-azurerm-backend@v4
       with:
         azure_credentials: ${{ secrets.AZURE_CREDENTIALS }}
         resource_group_name: myresourcegroup
         container_name: mycontainer
         storage_account_name: storageaccount432
     - name: terraform-apply
       run: terraform apply -auto-approve 
          
          
    
    
            
        
      


