name: action-infra  # project name

on:       #trigger 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 
    # paths-ignore:
    #   - .github/workflows/infra1.yml

env:
RESOURCE_NAME: ${{ secrets.RESOURCE_NAME }}
STORAGE_NAME: ${{ secrets.STORAGE_NAME }}
CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
KEY_NAME: ${{ secrets.KEY_NAME }}

jobs: 
  planning:   #job ka nam
    runs-on: ubuntu-latest    #runner ka nam
    steps:
      - name: repo-chekout
        uses: actions/checkout@v5   # task hai
      - name: az login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDITIONAL }}
      - name: setup-terrform
        uses: hashicorp/setup-terraform@v3
      - name: Terraform Init
        run: |
          terraform init \
            -backend-config="storage_account_name=${{ secrets.STORAGE_NAME }}" \
            -backend-config="container_name=${{ secrets.CONTAINER_NAME }}" \
            -backend-config="key=${{ secrets.KEY_NAME }}" \
            -backend-config="resource_group_name=${{ secrets.RESOURCE_NAME }}"
            
        
      
